version: '3.9'
services:
  db:
    image: mysql:8.0
    volumes:
      - new_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
      - bundle_cache:/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_cache:
  new_mysql_data:
